In [ ]:
#Activity Log
**Bolortulga Seded**
**11 February 2026**
**Week 1**
**Tasks:** shape, head(), tail(), info(), describe()

In [1]:
import pandas as pd
excel_file = 'movies.xls'
movies = pd.read_excel(excel_file)

In [2]:
print(movies.shape)

(1338, 25)

In [3]:
movies.tail()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
1333,Twin Falls Idaho,1999,Drama,English,USA,R,111,1.85,500000.0,985341.0,...,980,505,482.0,3166,180,0,3479,87,54.0,7.3
1334,Universal Soldier: The Return,1999,Action|Sci-Fi,English,USA,R,83,1.85,24000000.0,10431220.0,...,2000,577,485.0,4024,401,0,24216,162,75.0,4.1
1335,Varsity Blues,1999,Comedy|Drama|Romance|Sport,English,USA,R,106,1.85,16000000.0,52885587.0,...,23000,255,35.0,23369,0,0,35312,267,67.0,6.4
1336,Wild Wild West,1999,Action|Comedy|Sci-Fi|Western,English,USA,PG-13,106,1.85,170000000.0,113745408.0,...,10000,4000,582.0,15870,0,2,129601,648,85.0,4.8
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,811,586,362.0,2497,858,3,14747,338,85.0,4.1

In [4]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Title                        1338 non-null   str
 1   Year                         1338 non-null   int64
 2   Genres                       1338 non-null   str
 3   Language                     1333 non-null   str
 4   Country                      1338 non-null   str
 5   Content Rating               1316 non-null   str
 6   Duration                     1338 non-null   int64
 7   Aspect Ratio                 1308 non-null   float64
 8   Budget                       1281 non-null   float64
 9   Gross Earnings               1086 non-null   float64
 10  Director                     1338 non-null   str
 11  Actor 1                      1338 non-null   str
 12  Actor 2                      1338 non-null   str
 13  Actor 3                      1336 non-null   str
 14  Facebook Likes - Director    1338 non-null   int64
 15  Facebook Likes - Actor 1     1338 non-null   int64
 16  Facebook Likes - Actor 2     1338 non-null   int64
 17  Facebook Likes - Actor 3     1336 non-null   float64
 18  Facebook Likes - cast Total  1338 non-null   int64
 19  Facebook likes - Movie       1338 non-null   int64
 20  Facenumber in posters        1338 non-null   int64
 21  User Votes                   1338 non-null   int64
 22  Reviews by Users             1338 non-null   int64
 23  Reviews by Crtiics           1335 non-null   float64
 24  IMDB Score                   1338 non-null   float64
dtypes: float64(6), int64(10), str(9)
memory usage: 261.5 KB

In [5]:
movies.describe()

,Year,Duration,Aspect Ratio,Budget,Gross Earnings,Facebook Likes - Director,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
count,1338.000000,1338.000000,1308.000000,1.281000e+03,1.086000e+03,1338.000000,1338.000000,1338.000000,1336.000000,1338.000000,1338.000000,1338.000000,1.338000e+03,1338.000000,1335.000000,1338.000000
mean,1987.289985,113.071001,1.987752,2.712064e+07,4.752741e+07,1026.567265,5255.186846,1227.041106,456.738772,7673.354260,2656.870703,1.167414,8.538817e+04,255.183857,85.108614,6.702167
std,14.124870,27.434048,0.310047,8.466937e+07,6.113161e+07,3446.329257,8652.096738,2891.932284,880.031542,11055.985788,7446.142461,1.608806,1.560198e+05,343.287920,62.040982,1.066497
min,1916.000000,25.000000,1.180000,7.000000e+03,5.494000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000e+00,1.000000,1.000000,2.300000
25%,1982.000000,96.000000,1.850000,4.000000e+06,8.182800e+06,6.000000,605.000000,273.000000,136.000000,1412.000000,0.000000,0.000000,9.905500e+03,77.250000,39.000000,6.100000
50%,1993.000000,107.000000,1.850000,1.400000e+07,2.724075e+07,56.500000,925.500000,559.000000,324.000000,2660.000000,17.500000,1.000000,3.370500e+04,159.000000,71.000000,6.800000
75%,1997.000000,123.000000,2.350000,3.300000e+07,6.358500e+07,272.000000,10000.000000,849.000000,586.500000,11937.750000,812.000000,2.000000,9.031425e+04,306.750000,118.000000,7.400000
max,1999.000000,330.000000,2.760000,2.400000e+09,6.586723e+08,21000.000000,49000.000000,29000.000000,13000.000000,74382.000000,108000.000000,15.000000,1.689764e+06,4144.000000,392.000000,9.300000